version: '3'
services:
  daemon:
    build: .
    command: sh dk_init.sh
    volumes:
      - .:/app
    networks:
      - default-network
  web:
    image: pan0x744/muchat-react:20230518
    # build:
    #   context: ../muchat-react
    #   dockerfile: Dockerfile
    ports:
     - "0.0.0.0:3000:80"
    networks:
      - default-network
    environment:
      - REACT_APP_HOSTNAME=${REACT_APP_HOSTNAME}
    # command: sleep 999999
  admin:
    image: pan0x744/muchat-laravel:20230517
    ports:
      - "0.0.0.0:8000:8000"
      - "5173:5173"
    networks:
      - default-network
    depends_on:
      - db
    command: sh -c "/wait && sh dk_init.sh && php artisan serve --host=0.0.0.0"
    # command: sh -c "/wait && sleep 999999"
    environment:
      - WAIT_HOSTS=db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=3
      - WAIT_HOST_CONNECT_TIMEOUT=3
      - DB_HOST=db
  api:
    image: pan0x744/muchat-go:20230517
    ports:
      - "0.0.0.0:8080:8080"
    networks:
      - default-network
    depends_on:
      - db
    command: sh -c "/wait && ./bin/go_another_chatgpt"
    # command: sh -c "/wait && sleep 999999"
    environment:
      - WAIT_HOSTS=db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=3
      - WAIT_HOST_CONNECT_TIMEOUT=3
      - DB_HOST=db
      - DB_NAME=muchat
      - AP_BASE_URL=https://api.openai.com/v1/
  db:
    image: mysql:8.0
    volumes:
      - ./muchat-laravel/docker/db:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    networks:
      - default-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: muchat
      MYSQL_USER: ubuntu
      MYSQL_PASSWORD: ubuntu
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
networks:
  default-network: